# Generated by Django 4.1 on 2022-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('company_name', models.CharField(max_length=30)),
                ('describe_your_team_and_background', models.CharField(blank=True, max_length=100)),
                ('describe_your_company_and_product', models.CharField(blank=True, max_length=100)),
                ('what_is_unique_about_your_solution', models.CharField(max_length=100)),
                ('what_is_your_value_proposition_for_the_customer', models.CharField(max_length=100)),
                ('who_are_your_competetitors_and_what_is_your_competative_advantage', models.CharField(max_length=100)),
                ('explain_your_revenue_model', models.CharField(max_length=100)),
                ('what_is_the_potential_market_size_of_the_product', models.CharField(max_length=100)),
                ('how_do_you_market', models.CharField(max_length=100)),
            ],
        ),
    ]
