# Generated by Django 4.1 on 2022-08-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='describe_your_company_and_product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='describe_your_team_and_background',
            field=models.CharField(max_length=100),
        ),
    ]
