# Generated by Django 4.1 on 2022-08-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_registeruser_describe_your_company_and_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterUser',
            new_name='RegisterCompany',
        ),
    ]
