# Generated by Django 4.1 on 2022-08-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_registeruser_registercompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercompany',
            name='phone',
        ),
    ]
